---

# install default packages

- include: ../../../portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "git"
        entries:
          - "dev-vcs/git -perl -gpg -webdav"
    portage_packages:
      - { package: "app-editors/vim" }
      - { package: "dev-vcs/git" }
      - { package: "sys-process/htop" }
