---

# install default packages

- include: ../../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "git"
        entries:
          - "dev-vcs/git -perl -gpg -webdav"
    portage_packages:
      - { package: "sys-libs/ncurses", state: "unmerged" }
      - { package: "app-admin/sudo" }
      - { package: "app-editors/vim" }
      - { package: "dev-vcs/git" }
      - { package: "sys-process/htop" }
      - { package: "app-text/tree" }
