---

# fail when distribution is not supported

- name: check if distribution is supported
  fail: msg="'{{ ansible_distribution }}' is not supported by this role"
  when: ansible_distribution not in ["Gentoo"]


# install default packages

- import_tasks: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "git"
        entries:
          - "dev-vcs/git -perl -gpg -webdav"
    portage_packages:
      - { package: "app-admin/sudo" }
      - { package: "app-editors/vim" }
      - { package: "dev-vcs/git" }
      - { package: "sys-process/htop" }
      - { package: "app-text/tree" }
